# Generated by Django 5.0 on 2023-12-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.IntegerField(choices=[(1, 'Income'), (2, 'Expand')])),
                ('remark', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
