# Generated by Django 5.0 on 2023-12-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='remark',
            field=models.TextField(default='-'),
        ),
    ]
