# Generated by Django 5.0 on 2023-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_bill_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
